[package]
name = "okay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orx-imp-vec = "0.9.7"
smallvec = "1.11.2"
